name: release

on:
  workflow_dispatch:
    inputs:
      environment:
        type: component
        description: Select the component
      boolean:
        type: boolean
        description: True or False
      choice:
        type: choice
        description: Make a choice
        options:
        - foo
        - bar
        - baz
