name: release

on:
  workflow_dispatch:
    inputs:
      app:
        type: boolean
        description: Inclcue App
       

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2
        
      - name: Cleanup
        run: |
         echo " ${{ github.event.inputs.app }} "
          
