name: release

on:
  workflow_dispatch:
    inputs:
      component:
        type: choice
        description: Make a choice of component for release
        options:
        - App
        - Databse
        - Batch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2
        
      - name: Cleanup
        run: |
         echo " ${{ github.event.inputs.component }} "
          
