name: release

on:
  workflow_dispatch:
    inputs:
      component:
        type: choice
        description: Make a choice of component for release
        options:
        - App
        - Databse
        - Batch
